    - name: Are the dir available ?
      find:
        paths: "{{ location }}"
        recurse: true
      register: found_files


    - name: Directory Unavailable Msg
      ansible.builtin.debug:
        msg: The Node {{ location }} is unavailable in the system
      when: found_files.matched == 0

    - name: end play when no files are found
      meta: end_play
      when: found_files.matched == 0
